# Generated by Django 5.0.3 on 2024-03-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_faceimage_delete_face_det'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('embedding', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='FaceImage',
        ),
    ]
