# Generated by Django 5.0.6 on 2024-05-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_embedding_imageembedding_embeddings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('face_embedding', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='ImageEmbedding',
        ),
    ]
