# Generated by Django 5.0.6 on 2024-05-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_registerface_delete_imageembedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="registerface",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="faces/"),
        ),
    ]
