# Generated by Django 5.0.6 on 2024-05-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_registerface_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaceRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "face_id",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                ("face_embedding", models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name="RegisterFace",
        ),
    ]
